config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  # signup
  get "signup" => "users#new", as: :users
  post "signup" => "users#create"
  # login, lougout
  get "login" => "sessions#new", as: :sessions
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  # trackings
  get "start" => "trackings#new", as: :trackings
  post "start" => "trackings#create"
  get "trackings" => "trackings#index"
  post "end/:id" => "trackings#end", as: :end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :rate, presence: true
  has_many :trackings
end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  belongs_to :user
  belongs_to :client

  def self.group_by_day(trackings)
    trackings.order('started_at desc').group_by { |t| t.started_at.beginning_of_day }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A^.+@.+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  has_many :clients
  has_many :trackings

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = logged_user(session_params)
    if user
      session[:user_id] = user.id
      redirect_to root_path
      flash[:success] = <<-eos
        Welcome to forsythia! Ready to
        #{view_context.link_to('work', '/start', class: 'text-strong')}?
      eos
    else
      redirect_to '/login'
      flash[:error] = "Sorry, but your email or password were wrong."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def logged_user(session_params)
    user = User.find_by_email(session_params[:email])
    return user if user && user.authenticate(session_params[:password])
    nil
  end
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  before_filter :authorize

  def new
    @tracking = current_user.trackings.new
    @clients = current_user.try(:clients)
  end

  def create
    @tracking = current_user.trackings.new(tracking_params)
    if @tracking.save
      redirect_to root_path
      flash[:success] = "Work must go on!"
    else
      render 'new'
    end
  end

  def update
  end

  def end
    tracking = current_user.trackings.find(params[:id])
    tracking.update(ended_at: Time.now)
    redirect_to '/trackings'
  end

  def edit
  end

  def index
    @trackings = Tracking.group_by_day(current_user.trackings)
  end

  private

  def tracking_params
    params.require(:tracking).permit(:started_at, :ended_at, :client_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
      flash[:success] = "Welcome to forsythia! You may login now."
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_time(time)
    time.strftime("%l:%M %p") if time
  end

  def formatted_day(time)
    time.strftime("%e") if time
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Forsythia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Raleway:100italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "shared/navigation" %>
  <%= render "shared/flash_messages" %>
  <%= yield %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <% object.errors.full_messages.each do |msg| %>
      <p>
        - <%= msg %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="flash flash-<%= key %>"><%= sanitize(value) %></div>
<% end %>

app/views/shared/_navigation.html.erb
<nav>
  <ul>
    <% if current_user %>
      <li><%= link_to current_user.name, '/trackings' %></li>
      <li><%= link_to "logout", "/logout",  method: :delete, class: "text-strong" %></li>
    <% else %>
      <li><%= link_to "sign up", "/signup" %></li>
      <li><%= link_to "login", login_path, class: "text-strong" %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_tracking.html.erb
  <div class="tracking">
      <p>
        <%= formatted_time(tracking.started_at) %>
        -
        <%= formatted_time(tracking.ended_at) %>
        <strong>
          <%= link_to('end', end_path(tracking), method: :post) unless tracking.ended_at.present? %>
        </strong>
      </p>
  </div>

app/views/trackings/index.html.erb
<% provide(:title, 'All trackings') %>
<div class="container">
  <div class="period">
    <%= @trackings.keys.first.strftime("%B %Y") %>
  </div>
  <% @trackings.each do |key, values| %>
    <p>
      <strong><i> <%= formatted_day(key) %>. </i></strong>
      <% values.each do |tracking| %>
        <%= render "shared/tracking", tracking: tracking %>
      <% end %>
    </p>
  <% end %>
</div>

app/views/trackings/new.html.erb
<% provide(:title, 'Start new tracking') %>
<div class="form">
  <%= form_for(@tracking) do |f| %>
    <%= f.label :client %>
    <div class="select">
      <%= f.collection_select(:client_id, @clients, :id, :name, :prompt => 'Select') %>
    </div>
    <%= f.label :started_at %>
    <div class="select">
      <%= f.datetime_select :started_at %>
    </div>
    <%= f.submit "start", class: "button" %>
    <%= render 'shared/error_messages', object: f.object %>
  <% end %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="form">
  <%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign up", class: "button" %>

  <%= render 'shared/error_messages', object: f.object %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="welcome">
  <div class="welcome-logo">
    <h1>forsythia</h1>
  </div>
</div>